# This is a basic workflow to help you get started with Actions.....

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
#       - name: Check commit message
#         run: |
#            if [[ "${{ github.event.head_commit.message }}" == "hotfix" ]]; then
#             echo "Commit message contains 'hotfix'. Skipping linter..."
#             touch SKIP_LINTE
#            fi       
#       # Runs a single command using the runners shell
#       - name: lint
#         if: !contains(github.event.head_commit.message, 'SKIP_LINTER')
#         uses: golangci/golangci-lint-action@v3
#         with:
#           version: v1.51.0
#           args: --timeout 10m
#           skip-pkg-cache: true
#           skip-build-cache: true
      - name: Check commit message and run golangci-lint
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -i -q "hotfix"; then
            echo "Commit message contains 'hotfix'. Skipping golangci-lint..."
            touch SKIP_LINTER
          else
            echo "Commit message doesn't contain 'hotfix'. Running golangci-lint..."
            golangci/golangci-lint-action@v3
            with:
              version: v1.51.0
              args: --timeout 10m
              skip-pkg-cache: true
              skip-build-cache: true
          fi
              

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
